services:
    backend:
        build: ./backend
        container_name: worksquad_backend
        restart: always
        expose:
            - "8000"
        env_file:
            - backend/.env.local

    nginx:
        image: nginx:latest
        container_name: worksquad_nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - backend

    db:
        image: postgres:15-alpine
        container_name: worksquad_db
        restart: always
        volumes:
        - postgres_data:/var/lib/postgresql/data
        env_file: backend/.env.local
        ports:
        - "5432:5432"

volumes:
    postgres_data:
